version: "3.9"

services:
  backend:
    build: ./backend
    container_name: roboflow-backend
    ports:
      - "4000:4000"
    volumes:
      - C:/Users/DELL/Downloads/roboflow-filter-app/roboflow-filter-app/train:/app/train
    working_dir: /app
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    container_name: roboflow-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always